baseURL: https://masputrawae.github.io
title: MasPutraWae
languageCode: id
defaultContentLanguage: id
timeZone: Asia/Jakarta
copyright: Copyright Â© 2025 Putra Jaya. Licensed under CC BY-SA 4.0.

buildFuture               : true
enableEmoji               : true
enableRobotsTXT           : true

# ========== SERVICES ========== #
services:
  googleAnalytics:
    id: G-W9TMTZZYG5

# ========== PRIVACY ========== #
privacy:
  googleAnalytics:
    disable           : false
    respectDoNotTrack : true

# ========== SITEMAP ========== #
sitemap:
  changefreq    : 'monthly'
  disable       : false
  filename      : sitemap.xml
  priority      : 1

# ========== PAGINATION ========== #
pagination:
  pagerSize: 5
  path: halaman

# ========== IMAGING ========== #
imaging:
  quality: 100

# ========== PARAMS ========== #
params:
  description: Tempat meluangkan waktu untuk bercerita, dan berbagi ilmu. Dan yang pasti juga, untuk bersenang-senang.
  images:
    - default-image.webp

  author:
    name: Putra Jaya
    email: masputrawae.official@gmail.com

  social:
    twitter: masputrawae
    facebook_admin: 61583431824984

  socialLinks:
    - name: Twitter X
      href: https://x.com/masputrawae
      icon: twitter-x

    - name: Instagram
      href: https://www.instagram.com/masputrawae/
      icon: instagram

    - name: Github
      href: https://github.com/masputrawae
      icon: github

    - name: Feed
      href: index.xml
      icon: rss

    - name: Facebook
      href: https://www.facebook.com/profile.php?id=61583431824984
      icon: facebook

    - name: Discord
      href: https://discord.gg/nM4EP8DJFZ
      icon: discord

  shareButtons:
    facebook: true
    twitter: true
    linkedin: true
    whatsapp: true
    telegram: true
    reddit: true
    pinterest: true
    line: true
    mastodon: true
    mail: true

# ========== MENUS ========== #
menus:
  main:
    - name: Home
      pageRef: /
      weight: 10

    - name: Posts
      pageRef: /posts
      weight: 20

    - name: Notes
      pageRef: /notes
      weight: 30

    - name: Archives
      pageRef: /archives
      weight: 40

    - name: Search
      pageRef: /search
      weight: 50

# ========== OUTPUT ========== #
mediaType: "application/json"
outputFormats:
  search:
    mediaType: "application/json"
    baseName: "search"
    isPlainText: true
    notAlternative: true
  sitemap:
    mediaType: application/xml
    baseName: sitemap
    isPlainText: false
    notAlternative: true
  sitemapindex:
    mediaType: application/xml
    baseName: sitemapindex
    isPlainText: false
    notAlternative: true

outputs:
  home:
    - search
    - html
    - sitemapindex
    - rss
  section:
    - html
    - sitemap
    - rss

# ========== BUILD ========== #
build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: 'assets/.*\.(js|ts|jsx|tsx)'
      target: js
    - source: 'assets/.*\.(.*)$'
      target: $1

# ========== MODULES ========== #
module:
  hugoVersion:
    extended: true
    min: "0.152.2"

  mounts:
    - source: assets
      target: assets

    - source: static
      target: static

    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json

    - source: node_modules/bootstrap-icons/icons
      target: assets/icons

# ========== MARKUP ========== #
markup:
  highlight:
    style: github-dark
  goldmark:
    renderHooks:
      image:
        useEmbedded: auto
      link:
        useEmbedded: auto
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      passthrough:
        enable: true
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true